---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "nronne"
subtitle: "dashboard"
logo: "assets/logo.png"
# icon: "fas fa-skull-crossbones" Optional icon
footer: '<p>© Nikolaj Rønne 2020 | Created with Homer <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>'  # set false if you want to hide it.

# Optional message
message:
  # url: https://....
  style: "is-dark" # See https://bulma.io/documentation/components/message/#colors for styling options.
  title: "Attention" 
  content: "Get off my site! /nronne"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "github"
    icon: "fab fa-github"
    url: "https://github.com/nronne/"
    target: '_blank' # optionnal html a tag target attribute
  - name: "Blackboard"
    icon: "fas fa-book"
    url: "https://blackboard.au.dk/webapps/portal/execute/tabs/tabAction?tab_tab_group_id=_132_1"
  - name: "AU mail"
    icon: "fab fa-envelope"
    target: "https://post.au.dk/roundcube/"

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Home Server"
    icon: "fas fa-server"
    items:
      - name: "Nextcloud"
        logo: "assets/tools/nextcloud.png"
        subtitle: "private cloud service"
        tag: "NC"
        url: "https://cloud.nronne.dk/"
        target: '_blank'
      - name: "Webmin"
        logo: "assets/tools/webmin.png"
        url: "192.168.8.201/:10000"
      - name: "Cloudflare"
        logo: "assets/tools/cloudflare.png"
        tag: "CF"
        url: "https://www.cloudflare.com/"
  - name: "DevOps"
    icon: "fas fa-code-branch"
    items:
      - name: "Jenkins"
        logo: "assets/tools/jenkins.png"
        subtitle: "Continuous integration server"
        tag: "CI"
        url: "https://jenkins.io/"
        target: '_blank' # optionnal html a tag target attribute
      - name: "RabbitMQ Management"
        logo: "assets/tools/rabbitmq.png"
        subtitle: "Manage & monitor RabbitMQ server"
        tag: "haproxy"
        # Optional tagstyle
        # Same styling options as the optional message.
        tagstyle: "is-success"
        url: "https://www.rabbitmq.com/"
  - name: "Monitoring"
    icon: "fas fa-heartbeat"
    items:
      - name: "M/Monit"
        logo: "assets/tools/monit.png"
        subtitle: "Monitor & manage all monit enabled hosts"
        tag: "monit"
        url: "https://mmonit.com/monit/"
      - name: "Grafana"
        logo: "assets/tools/grafana.png"
        subtitle: "Metric analytics & dashboards"
        url: "https://grafana.com/"
      - name: "Kibana"
        logo: "assets/tools/elastic.png"
        subtitle: "Explore & visualize logs"
        tag: "elk"
        url: "https://www.elastic.co/products/kibana"
      - name: "Website monitoring"
        logo: "assets/tools/pingdom.png"
        subtitle: "Pingdom public reports overview"
        tag: "CI"
        url: "https://www.pingdom.com/"
